language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.3
otp_release:
  - 18.3
  - 19.3
  - 20.3
sudo: false
script: mix test
matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.3
    - elixir: 1.5.3
      otp_release: 18.3
    - elixir: 1.5.3
      otp_release: 19.3
    - elixir: 1.6.3
      otp_release: 18.3
    - elixir: 1.6.3
      otp_release: 19.3
