language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
otp_release:
  - 18.3
  - 19.0
  - 19.1
  - 19.2
  - 19.3
  - 20.0
  - 20.1
  - 20.2
sudo: false
script: mix test
matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.0
    - elixir: 1.3.4
      otp_release: 20.1
